automountServiceAccountToken: false
priorityClassName: system-node-critical

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

securityContext:
  privileged: true

nodeSelector:

tolerations: []

affinity: {}
